[lint]
extend-select = ["I"]

[lint.per-file-ignores]
"scripts/*" = ["E402", "RUF013", "RUF005", "F841"]
"notebooks/*" = ["B905", "E402", "F841"]
"tests/*" = ["RUF059", "E402", "F841"]
"backend/scripts/*" = ["E402", "RUF013", "RUF005", "F841"]
"backend/notebooks/*" = ["B905", "E402", "F841"]
"backend/tests/*" = ["RUF059", "E402", "F841"]
